### ISSUE TITLE
Update commands to use new zephyr repo name

### ISSUE THREAD

**Issue by szczys** [golioth/docs#37]
Please see the attached patch that updates `zephyr.git` to `zephyr-sdk.git` to match the renaming of the repo. This fixes an error that `west update` throws when using the old repo name:

```
$ west init -m git@github.com:golioth/zephyr.git --mr main ~/zephyrproject
$ cd zephyrproject
$ west update
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.8/site-packages/west/manifest.py", line 172, in _mpath
    path = cp.get('manifest', 'path')
  File "/usr/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'manifest'
```
[0001-Renamed-repo-to-fix-error-when-running.txt](https://github.com/golioth/docs/files/7071505/0001-Renamed-repo-to-fix-error-when-running.txt)

**Comment by szczys** [comment]
This issues is outdated and has been fixed in the docs.
