### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools_rust'

### ISSUE THREAD

**Issue by szczys** [golioth/docs#61]
Error thrown when running `pip install -r ~/compile/zephyrproject/zephyr/scripts/requirements.txt` within a virtual environment [per the docs](https://docs.golioth.io/hardware/esp32/quickstart/set-up-zephyr#install-zephyr-sdk).

```
(.venv) mike@Nelson:~/compile/zephyrproject$ pip install -r ~/compile/zephyrproject/zephyr/scripts/requirements.txt
Ignoring windows-curses: markers 'sys_platform == "win32"' don't match your environment
Collecting pyelftools>=0.26 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/6f/50/3d7729d64bb23393aa4c166af250a6e6f9def40c90bf0e9af3c5ad25b6f7/pyelftools-0.27-py2.py3-none-any.whl
Requirement already satisfied: PyYAML>=5.1 in ./.venv/lib/python3.6/site-packages (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 11))
Requirement already satisfied: pykwalify in ./.venv/lib/python3.6/site-packages (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 14))
Collecting canopen (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/bd/c3/5c030d96701c80c9c092c6082f959afc712c4256cc1c95267c56ef9d30e2/canopen-1.2.1-py3-none-any.whl
Requirement already satisfied: packaging in ./.venv/lib/python3.6/site-packages (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 18))
Collecting progress (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/2a/68/d8412d1e0d70edf9791cbac5426dc859f4649afc22f2abbeb0d947cf70fd/progress-1.6.tar.gz
Collecting psutil (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/e1/b0/7276de53321c12981717490516b7e612364f2cb372ee8901bd4a66a000d7/psutil-5.8.0.tar.gz
Collecting pylink-square (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/9b/55/5d454c0d4a8edaa69643d8218417f43e38d7b747bc74c098fdb3e9e353e3/pylink_square-0.11.1-py2.py3-none-any.whl
Collecting anytree (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 24))
  Using cached https://files.pythonhosted.org/packages/a8/65/be23d8c3ecd68d40541d49812cd94ed0f3ee37eb88669ca15df0e43daed1/anytree-2.8.0-py2.py3-none-any.whl
Collecting intelhex (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 27))
  Using cached https://files.pythonhosted.org/packages/97/78/79461288da2b13ed0a13deb65c4ad1428acb674b95278fa9abf1cefe62a2/intelhex-2.3.0-py2.py3-none-any.whl
Requirement already satisfied: west>=0.10.1 in ./.venv/lib/python3.6/site-packages (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 30))
Requirement already satisfied: colorama in ./.venv/lib/python3.6/site-packages (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 7))
Collecting ply>=3.10 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Collecting gcovr>=4.2 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/a8/43/3292324f9054d8f3b87c36cb64d9cf63513fe9d1d1a1b95df7b1dc92fb31/gcovr-5.0-py2.py3-none-any.whl
Collecting coverage (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/bd/75/3d80fa937c4ff5d1d47a5be5f9a92b6b6ebf365172d94f0c8c5a5692f9c5/coverage-6.0.2-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Collecting pytest (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/40/76/86f886e750b81a4357b6ed606b2bcf0ce6d6c27ad3c09ebf63ed674fc86e/pytest-6.2.5-py3-none-any.whl
Collecting mypy (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/59/f0/6b607fd2a18a0f0235d77b269e0ffe6abf4fe89e441f93ba3c14dd181ba9/mypy-0.910-cp36-cp36m-manylinux1_x86_64.whl
Collecting mock>=4.0.1 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/5c/03/b7e605db4a57c0f6fba744b11ef3ddf4ddebcada35022927a2b5fc623fdf/mock-4.0.3-py3-none-any.whl
Collecting breathe!=4.29.0,~=4.23 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/dd/3c/cf7386ab7c0b353a99265dd15081895f5efd79a4a2d02deae0d60c85d25b/breathe-4.31.0-py3-none-any.whl
Collecting sphinx~=3.3 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/a3/e7/9af5e0766e801cf0ad64eedab70dcea17646c3a0d309980b25426ccc53ec/Sphinx-3.5.4-py3-none-any.whl
Collecting sphinx_rtd_theme<1.0,>=0.5.2 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/ac/24/2475e8f83519b54b2148d4a56eb1111f9cec630d088c3ffc214492c12107/sphinx_rtd_theme-0.5.2-py2.py3-none-any.whl
Collecting sphinx-tabs (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/15/be/4fa8ecfb7a9ba5e8d5aa6e27351faaf5f20c9066652064e473a853431916/sphinx_tabs-3.2.0-py3-none-any.whl
Collecting sphinxcontrib-svg2pdfconverter (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/09/3d/12c03c19e997c66e1bb74a4d880c61b2c7d08d6a6e07b9176b3e39192014/sphinxcontrib_svg2pdfconverter-1.1.1-py3-none-any.whl
Collecting pygments~=2.9 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/78/c8/8d9be2f72d8f465461f22b5f199c04f7ada933add4dae6e2468133c17471/Pygments-2.10.0-py3-none-any.whl
Collecting sphinx-notfound-page>=0.6 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/94/a1/16fe95dabfa4ce57b1eb68d4154035ed1f0e09de4d1205fbc64cb69c8dd2/sphinx_notfound_page-0.7.1-py3-none-any.whl
Collecting pyserial (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl
Collecting pyocd>=0.29.0 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/d2/0c/8de157e63c01253a58e3e4227dae1994cc08923f485bea384cfe64ae5e8d/pyocd-0.32.0-py3-none-any.whl
Collecting tabulate (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/ca/80/7c0cad11bd99985cfe7c09427ee0b4f9bd6b048bd13d4ffb32c6db237dfb/tabulate-0.8.9-py3-none-any.whl
Collecting cbor>=1.0.0 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/9b/99/01c6a987c920500189eb74a291bd3a388e6c7cf85736bb6b066d9833315e/cbor-1.0.0.tar.gz
Collecting gitlint (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/0d/1d/8e695c3dcdf17cd087938ca01064c4eedb4fa06b8b6baa7f2688159c590f/gitlint-0.16.0-py2.py3-none-any.whl
Collecting junit2html (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/6b/a8/1d1f2927637d05005b20b313e37e4caa47d9d910945bc8439337a9c7015a/junit2html-30.0.6-py3-none-any.whl
Collecting lpc_checksum (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/92/ea/55fe6540369d1ee999f0a8647a04692e003fdf9330dd6b4ee076a4a8bb3d/lpc_checksum-2.2.0-py3-none-any.whl
Collecting Pillow (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/6f/2b/7c242e58b1b332a123b4a7bf358e2cc7fa7d904b3576b87defc9528e2bfd/Pillow-8.3.2-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
Collecting imgtool>=1.7.1 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/36/91/91a26e93eb6a499c135c0c7599bdf7c6453920d35d42d3577aa07c371759/imgtool-1.8.0-py3-none-any.whl
Collecting protobuf (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/ec/2e/309682e1fe979b17d6fec004e8107a953d1300b93c32c397a9c3ca60322e/protobuf-3.18.1-py2.py3-none-any.whl
Collecting PyGithub (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/c1/1f/9dc4ba315eeea222473cf4c15d3e665f32d52f859d9d6e73219d0a408969/PyGithub-1.55-py3-none-any.whl
Collecting python-magic (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-compliance.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/d3/99/c89223c6547df268596899334ee77b3051f606077317023617b1c43162fb/python_magic-0.4.24-py2.py3-none-any.whl
Collecting junitparser<2 (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-compliance.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/01/96/e3e973c23fb90eb69163de48040497ae3ed550042b50559736e69ad42274/junitparser-1.6.3-py2.py3-none-any.whl
Collecting pylint (from -r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-compliance.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/37/42/948d1486727806df2e0016f1cfc2d3beafe289f96d53dfc85d967f79afc5/pylint-2.11.1-py3-none-any.whl
Requirement already satisfied: ruamel.yaml>=0.16.0 in ./.venv/lib/python3.6/site-packages (from pykwalify->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 14))
Requirement already satisfied: docopt>=0.6.2 in ./.venv/lib/python3.6/site-packages (from pykwalify->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 14))
Requirement already satisfied: python-dateutil>=2.8.0 in ./.venv/lib/python3.6/site-packages (from pykwalify->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 14))
Collecting python-can>=3.0.0 (from canopen->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/97/dd/5e5ae96db41ba57dde127e0600c3d324239ed692e167296c5fdb992cbf41/python-can-3.3.4.tar.gz
Requirement already satisfied: pyparsing>=2.0.2 in ./.venv/lib/python3.6/site-packages (from packaging->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 18))
Collecting future (from pylink-square->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
Requirement already satisfied: six in ./.venv/lib/python3.6/site-packages (from pylink-square->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 21))
Requirement already satisfied: setuptools in ./.venv/lib/python3.6/site-packages (from west>=0.10.1->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-base.txt (line 30))
Collecting jinja2 (from gcovr>=4.2->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/94/42/d8bca8e99789bcc35dfa9b03acaa8b518720d6e060163745bc2bf2ead842/Jinja2-3.0.2-py3-none-any.whl
Collecting lxml (from gcovr>=4.2->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/1f/1d/a4485412268b38043a6c0f873245b5d9315c6615bcf44776759a2605dca5/lxml-4.6.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting pluggy<2.0,>=0.12 (from pytest->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/9e/01/f38e2ff29715251cf25532b9082a1589ab7e4f571ced434f98d0139336dc/pluggy-1.0.0-py2.py3-none-any.whl
Collecting toml (from pytest->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl
Collecting iniconfig (from pytest->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/9b/dd/b3c12c6d707058fa947864b67f0c4e0c39ef8610988d7baea9578f3c48f3/iniconfig-1.1.1-py2.py3-none-any.whl
Collecting attrs>=19.2.0 (from pytest->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/20/a9/ba6f1cd1a1517ff022b35acd6a7e4246371dfab08b8e42b829b6d07913cc/attrs-21.2.0-py2.py3-none-any.whl
Collecting py>=1.8.2 (from pytest->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/67/32/6fe01cfc3d1a27c92fdbcdfc3f67856da8cbadf0dd9f2e18055202b2dc62/py-1.10.0-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12; python_version < "3.8" (from pytest->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/71/c2/cb1855f0b2a0ae9ccc9b69f150a7aebd4a8d815bd951e74621c4154c52a8/importlib_metadata-4.8.1-py3-none-any.whl
Collecting mypy-extensions<0.5.0,>=0.4.3 (from mypy->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/5c/eb/975c7c080f3223a5cdaff09612f3a5221e4ba534f7039db34c35d95fa6a5/mypy_extensions-0.4.3-py2.py3-none-any.whl
Collecting typed-ast<1.5.0,>=1.4.0; python_version < "3.8" (from mypy->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/7e/4b/d7377c5d25b5c3b2682dada2eee1086b23842f3eb76e41063436aa4e302f/typed_ast-1.4.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting typing-extensions>=3.7.4 (from mypy->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-build-test.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/74/60/18783336cc7fcdd95dae91d73477830aa53f5d3181ae4fe20491d7fc3199/typing_extensions-3.10.0.2-py3-none-any.whl
Collecting docutils>=0.12 (from breathe!=4.29.0,~=4.23->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/4c/5e/6003a0d1f37725ec2ebd4046b657abb9372202655f96e76795dca8c0063c/docutils-0.17.1-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Collecting sphinxcontrib-jsmath (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c2/42/4c8646762ee83602e3fb3fbe774c2fac12f317deb0b5dbeeedd2d3ba4b77/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl
Collecting sphinxcontrib-qthelp (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/2b/14/05f9206cf4e9cfca1afb5fd224c7cd434dcc3a433d6d9e4e0264d29c6cdb/sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl
Collecting sphinxcontrib-serializinghtml (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c6/77/5464ec50dd0f1c1037e3c93249b040c8fc8078fdda97530eeb02424b6eea/sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl
Collecting imagesize (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/31/b2/b5522a0c8d11e4aff83f8342f3f0dea68c2fb25aa44403e420587f0ce204/imagesize-1.2.0-py2.py3-none-any.whl
Collecting requests>=2.5.0 (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/92/96/144f70b972a9c0eabbd4391ef93ccd49d0f2747f4f6a2a2738e99e5adc65/requests-2.26.0-py2.py3-none-any.whl
Collecting sphinxcontrib-applehelp (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/dc/47/86022665a9433d89a66f5911b558ddff69861766807ba685de2e324bd6ed/sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/f6/6e/7e07970c90a57c21da92013c5ba47f8e9598c17e88cc35b008ca61225ed3/snowballstemmer-2.1.0-py2.py3-none-any.whl
Collecting sphinxcontrib-devhelp (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c5/09/5de5ed43a521387f18bdf5f5af31d099605c992fd25372b2b9b825ce48ee/sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl
Collecting sphinxcontrib-htmlhelp (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/63/40/c854ef09500e25f6432dcbad0f37df87fd7046d376272292d8654cc71c95/sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl
Collecting babel>=1.3 (from sphinx~=3.3->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-doc.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/aa/96/4ba93c5f40459dc850d25f9ba93f869a623e77aaecc7a9344e19c01942cf/Babel-2.9.1-py2.py3-none-any.whl
Collecting cmsis-pack-manager>=0.3.0 (from pyocd>=0.29.0->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/11/a2/c5cf8dfec98f9bcec8740d44e032862ffe6cdbd299e928b59ae26e2362ca/cmsis_pack_manager-0.3.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting intervaltree<4.0,>=3.0.2 (from pyocd>=0.29.0->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/50/fb/396d568039d21344639db96d940d40eb62befe704ef849b27949ded5c3bb/intervaltree-3.1.0.tar.gz
Collecting naturalsort<2.0,>=1.5 (from pyocd>=0.29.0->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/0c/84/ce1985c8c61d2ac21a4b3a5d586ed0794b855f925ecc47adca546f0c7022/naturalsort-1.5.1.tar.gz
Collecting capstone<5.0,>=4.0 (from pyocd>=0.29.0->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/38/85/647d512c2c2e2981d6f4c70ed41c5ec3d8d6f06cc9c9dd63348e8e6a21a3/capstone-4.0.2-py2.py3-none-manylinux1_x86_64.whl
Collecting prettytable<3.0,>=2.0 (from pyocd>=0.29.0->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/e1/77/821a93d77111aee2525841b6116287f99eeefc482f4f28765fd8d7ef1c64/prettytable-2.2.1-py3-none-any.whl
Collecting pyocd-pemicro>=1.0.6 (from pyocd>=0.29.0->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/e1/84/26abfc902ac2225d8a4478e190f4143973a6c9966949e54b8e711f078e36/pyocd_pemicro-1.0.6-py3-none-any.whl
Collecting pyusb<2.0,>=1.2.1 (from pyocd>=0.29.0->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/15/a8/4982498b2ab44d1fcd5c49f07ea3795eab01601dc143b009d333fcace3b9/pyusb-1.2.1-py3-none-any.whl
Collecting dataclasses; python_version < "3.7" (from pyocd>=0.29.0->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-run-test.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/fe/ca/75fac5856ab5cfa51bbbcefa250182e50441074fdc3f803f6e76451fab43/dataclasses-0.8-py3-none-any.whl
Collecting arrow==1.2.0 (from gitlint->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/d8/bd/9f0a4308b6b898c78dcbee4268b630c9a45922439043d45e608db6919e69/arrow-1.2.0-py3-none-any.whl
Collecting Click==8.0.1 (from gitlint->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/76/0a/b6c5f311e32aeb3b406e03c079ade51e905ea630fc19d1262a46249c1c86/click-8.0.1-py3-none-any.whl
Collecting sh==1.14.2; sys_platform != "win32" (from gitlint->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/7a/c3/0836b7b975d09428d90f926dc1f86e2d76d721cf79bd6659838761c35f85/sh-1.14.2-py2.py3-none-any.whl
Collecting cryptography>=2.4.2 (from imgtool>=1.7.1->-r /home/mike/compile/zephyrproject/zephyr/scripts/requirements-extras.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/10/91/90b8d4cd611ac2aa526290ae4b4285aa5ea57ee191c63c2f3d04170d7683/cryptography-35.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_j0tp4yg/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_j0tp4yg/cryptography/
```

The solution is to upgrade pip:

```
pip install --upgrade pip
```

should the pip upgrade be part of the installation steps? Installing `python3-pip` is already part of the dependencies step, but running that `apt` command didn't fix this issue, I had to run the pip command itself.

Here's my pip version info after the upgrade command:

```
$ pip -V
pip 21.3 from /home/mike/.local/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by szczys** [comment]
This issue is stale. If anyone is able to reproduce this, please reopen and we'll investigated.
